[package]
name = "horizon-atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
socket2 = "0.6.0"
sha1 = "0.10.5"
base64 = "0.22.1"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }