[server]
address = "0.0.0.0"
port = 3000
max_connections = 10000

[cluster]
node_id = "atlas-node-2"
discovery_interval = 30
health_check_interval = 10

[security]
enable_encryption = true
key_rotation_interval = 3600

[game_servers]
startup_timeout = 30
shutdown_timeout = 15
max_idle_time = 300

[regions]
preload_distance = 1000.0
transfer_distance = 500.0
sync_interval = 1

[compression]
enable = true
algorithm = "lz4"
threshold = 512

[logging]
level = "info"
format = "json"